import type { DeploymentSpec, TerraformVarsOutput } from './types.js'
import { getModule, isEuRegion } from './inventory.js'

const EU_TLD_PATTERN = /\.(ai|eu|fr|de|nl|it|es|cloud|net|com)$/

const escapeHcl = (s: string): string => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')

const hclString = (s: string): string => `"${escapeHcl(s)}"`

const hclList = (xs: ReadonlyArray<string>): string =>
  `[${xs.map((x) => hclString(x)).join(', ')}]`

const validateSpec = (spec: DeploymentSpec): void => {
  if (!spec.tenant_id || !/^[a-z0-9-]{3,40}$/.test(spec.tenant_id)) {
    throw new Error(`invalid tenant_id: ${spec.tenant_id}`)
  }
  if (spec.operator_wg_pubkeys.length === 0) {
    throw new Error('operator_wg_pubkeys must contain at least one entry')
  }
  if (spec.model_providers.length === 0) {
    throw new Error('model_providers must contain at least one EU domain')
  }
  for (const p of spec.model_providers) {
    if (!EU_TLD_PATTERN.test(p)) {
      throw new Error(`model provider "${p}" is not in the EU allowlist (TLD)`)
    }
  }
  if (spec.cloud !== 'aws' && !isEuRegion(spec.cloud, spec.region)) {
    throw new Error(`region "${spec.region}" is not EU-resident for cloud "${spec.cloud}"`)
  }
  if (spec.cloud === 'aws' && !isEuRegion('aws', spec.region)) {
    throw new Error(`region "${spec.region}" is not in the AWS EU set; sovereign tier requires eu-* regions`)
  }
}

export const generateTfVars = (spec: DeploymentSpec): TerraformVarsOutput => {
  validateSpec(spec)
  const mod = getModule(spec.cloud)

  const proxyCidr = spec.proxy_node_cidr ?? '10.0.0.0/32'
  const egressCidrs = spec.model_provider_egress_cidrs ?? []
  const sandboxCount = spec.sandbox_node_count ?? 2
  const packer = spec.packer_image_id ?? ''

  const lines = [
    `# Generated by @fuze-ai/agent-sovereign-terraform for tenant ${spec.tenant_id}.`,
    `tenant_id                   = ${hclString(spec.tenant_id)}`,
    `wireguard_public_keys       = ${hclList(spec.operator_wg_pubkeys)}`,
    `wireguard_public_keys_cidrs = ${hclList(spec.operator_wg_pubkeys.map(() => '0.0.0.0/32'))}`,
    `proxy_node_cidr             = ${hclString(proxyCidr)}`,
    `model_provider_allowlist    = ${hclList(spec.model_providers)}`,
    `model_provider_egress_cidrs = ${hclList(egressCidrs)}`,
    `kms_key_id                  = ${hclString(spec.kms_key_id)}`,
    `packer_image_id             = ${hclString(packer)}`,
    `sandbox_node_count          = ${sandboxCount}`,
    `region                      = ${hclString(spec.region)}`,
  ]

  const varsHcl = lines.join('\n') + '\n'

  const jsonObj: Record<string, unknown> = {
    tenant_id: spec.tenant_id,
    wireguard_public_keys: [...spec.operator_wg_pubkeys],
    wireguard_public_keys_cidrs: spec.operator_wg_pubkeys.map(() => '0.0.0.0/32'),
    proxy_node_cidr: proxyCidr,
    model_provider_allowlist: [...spec.model_providers],
    model_provider_egress_cidrs: [...egressCidrs],
    kms_key_id: spec.kms_key_id,
    packer_image_id: packer,
    sandbox_node_count: sandboxCount,
    region: spec.region,
  }
  const varsJson = JSON.stringify(jsonObj, null, 2) + '\n'

  return { module: mod.name, varsHcl, varsJson }
}
